# Generated by Django 4.1 on 2022-08-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='img/articles/default.png', upload_to='img/articles/%Y/%m/%d'),
        ),
    ]
